const cameraInput=document.getElementById("cameraInput"),galleryInput=document.getElementById("galleryInput"),preview=document.getElementById("preview"),placeholder=document.getElementById("previewPlaceholder"),photoInfo=document.getElementById("photoInfo"),photoName=document.getElementById("photoName"),uploadArea=document.getElementById("uploadArea"),result=document.getElementById("result"),analyzeButton=document.getElementById("analyzeButton");let selectedFile=null;
function openCamera(){cameraInput.click()}
function openGallery(){galleryInput.click()}
cameraInput.addEventListener("change",function(){if(this.files.length)handleImage(this.files[0])});
galleryInput.addEventListener("change",function(){if(this.files.length)handleImage(this.files[0])});
function handleImage(file){if(!file.type.startsWith("image/"))return alert("Please select a valid image.");if(file.size>15*1024*1024)return alert("Image is too large. Please select an image under 15 MB.");selectedFile=file;const reader=new FileReader();reader.onload=e=>{preview.src=e.target.result;preview.style.display="block";placeholder.style.display="none";photoInfo.classList.remove("hidden");photoName.textContent=file.name};reader.readAsDataURL(file);result.classList.add("hidden")}
function clearPhoto(){selectedFile=null;cameraInput.value="";galleryInput.value="";preview.src="";preview.style.display="none";placeholder.style.display="block";photoInfo.classList.add("hidden");result.classList.add("hidden")}
uploadArea.addEventListener("dragover",e=>{e.preventDefault();uploadArea.style.background="#edf9e9"});uploadArea.addEventListener("dragleave",()=>uploadArea.style.background="");uploadArea.addEventListener("drop",e=>{e.preventDefault();uploadArea.style.background="";if(e.dataTransfer.files[0])handleImage(e.dataTransfer.files[0])});
function analyzeSnake(){if(!selectedFile)return alert("Please take a photo or select a photo first.");analyzeButton.disabled=true;analyzeButton.textContent="🤖 Analyzing...";setTimeout(()=>{result.classList.remove("hidden");analyzeButton.disabled=false;analyzeButton.textContent="🤖 Analyze Snake";result.scrollIntoView({behavior:"smooth",block:"center"})},1200)}
function openIdentifier(){scrollToSection("identify")}
function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
function findHospitals(){const status=document.getElementById("locationStatus"),results=document.getElementById("hospitalResults"),link=document.getElementById("mapsLink");status.textContent="Requesting your location...";if(!navigator.geolocation){status.textContent="Location is not supported.";return}navigator.geolocation.getCurrentPosition(p=>{const {latitude,longitude}=p.coords;status.textContent="Location detected successfully.";link.href=`https://www.google.com/maps/search/hospital/@${latitude},${longitude},14z`;results.classList.remove("hidden")},()=>status.textContent="Location permission was denied. Please enable it in browser settings.",{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
document.getElementById("language").addEventListener("change",e=>{document.querySelector(".hero h1").innerHTML=e.target.value==="hi"?"साँप पहचानें। <span>जान बचाएँ।</span> प्रकृति बचाएँ।":"Identify Snakes. <span>Save Lives.</span> Protect Nature.";document.querySelector(".hero p").textContent=e.target.value==="hi"?"AI की मदद से साँप की पहचान, साँप के काटने पर प्राथमिक सहायता और आपातकालीन सहायता।":"AI-powered snake identification, snakebite first-aid guidance and emergency assistance for communities across India."});
